global:
  appVersion: 1.0.0-SNAPSHOT
  name: conix-web-unified
# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  #repository: cf1dck.cfavorita.net/ec.com.conixweb/conix-web-unified
  repository: gcr.io/conix-369616/conix-web-unified
  pullPolicy: Always
  tag: "1.0.0-SNAPSHOT"
imagePullSecrets:
  - name: cf-regcred
serviceAccount:
  # Specifies whether a service account should be created
  create: false
service:
  type: ClusterIP
  sessionAffinity: None
  port: 80
  targetPort: 80
ingress:
  enabled: true
  hosts:
    - host: 192.168.10.240
      paths:
        - /conixWebUnified/
resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 1m
    memory: 128Mi
env:
  COUNTRY_DEFINITION: EC

livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /conixWebUnified/actuator/health
    port: 80
    scheme: HTTP
  initialDelaySeconds: 240
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 240
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /conixWebUnified/actuator/health
    port: 80
    scheme: HTTP
  initialDelaySeconds: 240
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 240
